### ISSUE TITLE
Upgrade CDK to V2

### ISSUE THREAD

**Issue by YotillaJonas** [devopsbox-io/example-cdk-from-lambda#1]
The currently used version of CDK in this project is 1.71.0. However, V1 is in maintenance mode since June 1, 2022. See [https://github.com/aws/aws-cdk/issues/19836](https://github.com/aws/aws-cdk/issues/19836).

I have a working branch for this upgrade which I could push if I had the necessary permissions.

**Comment by mraszplewicz** [comment]
Thank you @YotillaJonas!

Can you fork the repo and create a Pull Request from your fork?

**Comment by mraszplewicz** [comment]
Thank you @YotillaJonas again for your contribution!

I've created the `cdk-v2` branch and merged your changes there. I don't want to merge it to `master` as it is referenced in my article, but I've added a note to the README.md.
